[package]
name = "cheetiedotpy/wcs"
description = "Extensible framework that allows you to create fully customizable combat systems easily by providing useful abstraction"
version = "2.5.0"
license = "MIT"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = ["**"]
include = ["include", "out", "include/**", "out/**", "LICENSE.txt", "node_modules", "node_modules/@rbxts", "node_modules/@flamework", "node_modules/@flamework/**", "node_modules/@rbxts/**", "default.project.json", "LICENSE", "wally.toml"]

[dependencies]